### ISSUE TITLE
title

### ISSUE THREAD

**Issue by chykon** [chykon/rohd#1]
### Describe the bug

sample text

* 1
* 2
* 3

### To Reproduce

1. Use class ... for ...
2. Run a simulation with ...
3. See error

test test

### Expected behavior

123

### Actual behavior

321

### Additional: Dart SDK info

text

### Additional: pubspec.yaml

```yaml
name: newtify
description: >-
  Have you been turned into a newt?  Would you like to be?
  This package can help. It has all of the
  newt-transmogrification functionality you have been looking
  for.
version: 1.2.3
homepage: https://example-pet-store.com/newtify
documentation: https://example-pet-store.com/newtify/docs

environment:
  sdk: '>=2.10.0 <3.0.0'
  
dependencies:
  efts: ^2.0.4
  transmogrify: ^0.4.0
  
dev_dependencies:
  test: '>=1.15.0 <2.0.0'
```

### Additional: Context

1 1 1
